### ISSUE TITLE
npm run sw - missing script

### ISSUE THREAD

**Issue by guma44** [nirgn975/Angular-Django-Seed-Project#77]
When I try to build the client image I get the error:
```
Step 11/13 : RUN npm run sw
 ---> Running in e2ea4451e26c
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm ERR! missing script: sw

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-21T20_47_44_765Z-debug.log

```

I am not sure what kind of script I should run :).

Thanks for help.

**Comment by nirgn975** [comment]
@guma44 Good catch, thanks!
In the latest update of Angular-CLI there is no `sw` npm script. They change it to `"serviceWorker": true,` in `.angular-cli.json` file (which is turn on in our case). So I'm there is no need to do this manually any more. A fix will go live very soon!

**Comment by guma44** [comment]
Thanks for explanation and fix!
